// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47UJqi0Qaor-zJwOdd-eccVX5yMU0JLE',
    appId: '1:553023711865:web:e166daf7566fd1a970c2a8',
    messagingSenderId: '553023711865',
    projectId: 'onstypractice',
    authDomain: 'onstypractice.firebaseapp.com',
    storageBucket: 'onstypractice.firebasestorage.app',
    measurementId: 'G-5QW49PMB70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiIyNcOICYDxVT7oqzs5RftDNo-bNrkI',
    appId: '1:553023711865:android:3dc336f72340ed3870c2a8',
    messagingSenderId: '553023711865',
    projectId: 'onstypractice',
    storageBucket: 'onstypractice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogpTnO0loeHjwcQ3Aw1N1NFzgkRM2OKQ',
    appId: '1:553023711865:ios:c7684b74e05a92fe70c2a8',
    messagingSenderId: '553023711865',
    projectId: 'onstypractice',
    storageBucket: 'onstypractice.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineLearningPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCogpTnO0loeHjwcQ3Aw1N1NFzgkRM2OKQ',
    appId: '1:553023711865:ios:c7684b74e05a92fe70c2a8',
    messagingSenderId: '553023711865',
    projectId: 'onstypractice',
    storageBucket: 'onstypractice.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineLearningPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47UJqi0Qaor-zJwOdd-eccVX5yMU0JLE',
    appId: '1:553023711865:web:f6370d7ff83d16d470c2a8',
    messagingSenderId: '553023711865',
    projectId: 'onstypractice',
    authDomain: 'onstypractice.firebaseapp.com',
    storageBucket: 'onstypractice.firebasestorage.app',
    measurementId: 'G-LHEBYVRJH6',
  );
}
