// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkblQWZkmCoojn7tRme9ygRYkfFCjFD3I',
    appId: '1:839282962415:web:ee45fc3fbf61dba7b1d01a',
    messagingSenderId: '839282962415',
    projectId: 'onlinelearningapp-10145',
    authDomain: 'onlinelearningapp-10145.firebaseapp.com',
    storageBucket: 'onlinelearningapp-10145.firebasestorage.app',
    measurementId: 'G-YXMD2D2R9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoDAqzCtOQtMuvEDmkXsad4bG3sPlSia4',
    appId: '1:839282962415:android:c2dd3c2555e2c7a8b1d01a',
    messagingSenderId: '839282962415',
    projectId: 'onlinelearningapp-10145',
    storageBucket: 'onlinelearningapp-10145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3Yno2hMOiDDwgESlyjIuhc8cS9w8Zmo',
    appId: '1:839282962415:ios:3685666c460145bcb1d01a',
    messagingSenderId: '839282962415',
    projectId: 'onlinelearningapp-10145',
    storageBucket: 'onlinelearningapp-10145.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineLearningPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA3Yno2hMOiDDwgESlyjIuhc8cS9w8Zmo',
    appId: '1:839282962415:ios:3685666c460145bcb1d01a',
    messagingSenderId: '839282962415',
    projectId: 'onlinelearningapp-10145',
    storageBucket: 'onlinelearningapp-10145.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineLearningPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkblQWZkmCoojn7tRme9ygRYkfFCjFD3I',
    appId: '1:839282962415:web:649aa4929a772166b1d01a',
    messagingSenderId: '839282962415',
    projectId: 'onlinelearningapp-10145',
    authDomain: 'onlinelearningapp-10145.firebaseapp.com',
    storageBucket: 'onlinelearningapp-10145.firebasestorage.app',
    measurementId: 'G-CQRZVE5EXY',
  );
}
